cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: false
      addresses: [ 172.16.12.10/24, 2001:dead:beef:1012::10/64 ]
      nameservers:
         addresses: [ 66.129.233.81 , 66.129.233.82]
      routes:
        - to: 0.0.0.0/0
          via: 172.16.12.1
          metric: 1
        - to: ::/0
          via: 2001:dead:beef:1012::1
          metric: 1
EOF

