
sudo hostname svr1
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:19:00:0c:63
      interfaces:
        - eth1
        - eth2
      parameters:
         mode: 802.3ad
      # addresses: [ 192.168.101.103/24, fc00:dead:beef:101::10:103/64]
      addresses: [ 192.168.101.1/24]
      gateway4: 192.168.101.254
      # gateway6: fc00:dead:beef:101::1
EOF





sudo hostname svr2
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml
network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 56:04:19:00:49:f1
      interfaces:
        - eth1
        - eth0
      parameters:
         mode: 802.3ad
      # addresses: [ 192.168.101.103/24, fc00:dead:beef:101::10:103/64]
      addresses: [ 192.168.102.2/24]
      gateway4: 192.168.102.254
      # gateway6: fc00:dead:beef:101::1
EOF

       



