---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app: metallb
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 172.16.11.1
      peer-asn: 65200
      my-asn: 65201
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 172.16.1.0/28
