---
apiVersion: v1
kind: Pod
metadata:
  name: client1
spec:
  containers:
  - name: webserver
    image: quay.io/m1r24n/webserver:0.1
    # imagePullPolicy: Always 
    securityContext:
      privileged: true
  nodeName: node1
---
apiVersion: v1
kind: Pod
metadata:
  name: client2
spec:
  containers:
  - name: webserver
    image: quay.io/m1r24n/webserver:0.1
    #imagePullPolicy: Always 
    securityContext:
      privileged: true
  nodeName: node2
