apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vm1
  name: vm1
  namespace: lab5
spec:
  domain:
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      interfaces:
      - name: default
        bridge: {}
    resources:
      requests:
        memory: 128M
  networks:
  - name: default
    pod: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: 172.16.14.10:5000/cirros:0.5.2
      path: /cirros-0.5.2-x86_64-disk.img
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |
        #cloud-config
        
        
    

